=begin
APPLICATION CONTROLLER – A parent controller that controls the flow of data/ request in admin related views
PROGRAMMER: Hsieh Tzuchun | Qin Yuren
PURPOSE: Allow access of navbar to the database | Sets cookie for 1st time visit
=end
class ApplicationController < ActionController::Base
    # Access proposal database before any action
    before_action :set_proposal
    # A method protecting the site from CSRF (Cross-Site Request Forgery)
    # Generates authenticity tokens when transmitting data
    protect_from_forgery
    # Auto-generated action for "devise" module
    before_action :configure_permitted_parameters, if: :devise_controller?
    # Sets up first time visit token
    before_action :first_time_visit?, unless: -> { cookies[:first_visit] }

    protected
    # Adding flash notice keywords
    add_flash_types :warning
    
  # If the user is on first time visit, redirect to welcome page
  def first_time_visit?
      cookies[:first_visit] = 1
      unless user_signed_in?
        redirect_to '/welcome'
      end
  end

  # Auto-generated by "Devise" module
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
  # Request data from proposal database for navbar notice
  def set_proposal
      @proposal_number = Proposal.all.size
      @proposal_exist = Proposal.first
  end

end
