=begin
HOMEPAGE CONTROLLER – Controls the flow of data/ requests in homepage views
PURPOSE: Allow access of pages to the database/ organsize gathered data in required formats
=end
class HomepageController < ApplicationController
  # Auto-generated by "Devise" module
  include Devise::Controllers::Helpers 

  # GET /homepage
  def index
  end

  # GET /homepage/about
  def about
  end
  
  # GET /homepage/contact
  def contact
  end
  
  # GET /homepage/overview
  def overview 
      if Comment.all.size>3
        @comments = Comment.last(3)
      else
        @comments = Comment.all
      end

      array = Array.new
      array[0] = ['Course', 'Workload', 'TeachingQuality', 'Faculty', 'Overall']
      i = 1
      Course.all.each do |course|
          array[i] = [course.code, course.workload, course.quality, course.faculty, course.overall]
          i = i + 1
      end
      @courses = array.to_json.html_safe
      # provide the arrays required by the visualization
      
      array2 = Array.new
      array2[0] = ['Course Code', 'Teaching Qulity', 'Workload', 'Usefulness', 'Difficulty', 'CGPA', 'Overall']
      i = 1
      Course.all.each do |course|
          array2[i] = [course.code, course.quality, course.workload, course.usefulness, course.difficulty, course.gpa, course.overall]
          i = i + 1
      end
      @courses2 = array2.to_json.html_safe
      # provide the arrays required by the visualization
  end
  
end
